name: Update Manifest

on:
  workflow_call:
    inputs:
      yaml_file:
        required: true
        type: string
      image_name:
        required: true
        type: string
      image_version:
        required: true
        type: string

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Commit Hash
        run: echo ${{ github.sha }} | head -c 7 > commit_hash.txt

      - name: Update Kubernetes Manifest
        run: |
          sed -i "s|image: ${{ inputs.image_name }}:.*|image: ${{ inputs.image_name }}:${{ inputs.image_version }}|" ${{ inputs.yaml_file }}

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ${{ inputs.yaml_file }}
          git commit -m "Update image version to ${{ inputs.image_version }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
