name: Update Manifest

on:
  workflow_call:
    inputs:
      yaml_file:
        required: true
        type: string
      image_name:
        required: true
        type: string
      image_version:
        required: true
        type: string

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Kubernetes Manifest
        run: |
          sed -i "s|image: ${INPUT_IMAGE_NAME}:.*|image: ${INPUT_IMAGE_NAME}:${INPUT_IMAGE_VERSION}|" ${INPUT_YAML_FILE}

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ${INPUT_YAML_FILE}
          git commit -m "Update image version to ${INPUT_IMAGE_VERSION}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
